name: NPM Alpha release

on:
  push:
    branches:
      - master

jobs:
  Alpha:
    name: Alpha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm version --git-tag-version=false $(awk -F '"' '/version/ { print $4 }' package.json)-alpha.$(date +%s)
      - run: npm publish --access=public --tag=alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
